---
- name: restart systemd-resolved
  become: true
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted

- name: reload systemd-resolved
  become: true
  ansible.builtin.systemd:
    name: systemd-resolved
    state: reloaded

- name: restart NetworkManager
  become: true
  ansible.builtin.systemd:
    name: NetworkManager
    state: restarted
